version: "3.9"

services:
  # MEMO: Redisがなくてもローカルで動作するので不要では？
  # redis:
  #   image: "redis:alpine"
  web:
    ports:
      - "5000:5000"
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: flask_web
    env_file: ./docker.env
