version: "3.9"

services:
  redis:
    image: "redis:alpine"
  pptx_copy_paste:
    image: pptx_copy_paste:5
    ports:
      - "5000:5000"
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: pptx_copy_paste_api
    env_file: ./docker.env
